name: Build and Test our Brain Teasers
on:
  push:
    branches: #when pushed on branch main
      - main
  pull_request: # when pull request opened on branch main
    branches:
      - main

jobs:
  build-and-test: # name of this job
    runs-on: ubuntu-latest #installs ubuntu on pipline vm
    steps:
      - name: Checkout our code #name of step
        uses: actions/checkout@v4 #prebuilt action that copies code over
      - name: Setup Dotnet #name of step
        uses: actions/setup-dotnet@v4 #prebuilt action to download dotnet on vm
        with: #with = options
          dotnet-version: '8.0.x' # specificying the version
      - name: Restore Packages #name of step
        run: dotnet restore #do this command
      - name: Build our code # name of step
        run: dotnet build #do this command = check if it builds
      - run: dotnet test # do this command = run tests
    deploy: # name of this job
        runs-on: windows-latest
        #this is referencing the job "build-and-test"
        needs: [build-and-test] #this is saying to deploy, first check this job works